#!/usr/bin/env python3
import argparse
import hmac
import json
import os
import re
import sys
import threading
import uuid
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, Dict, List, Optional


TOOLS = [
    {
        "name": "list_dir",
        "description": "List files and folders inside the PC workspace.",
        "args": {
            "path": "Relative directory path, usually '.' for the workspace root.",
        },
    },
    {
        "name": "read_file",
        "description": "Read a text file from the PC workspace.",
        "args": {
            "path": "Relative file path inside the workspace.",
        },
    },
    {
        "name": "write_file",
        "description": "Create or replace a text file inside the PC workspace.",
        "args": {
            "path": "Relative file path inside the workspace.",
            "content": "Full file contents as a UTF-8 string.",
        },
    },
]
ALLOWED_TOOL_NAMES = {tool["name"] for tool in TOOLS}
MAX_REQUEST_BYTES = int(os.environ.get("AGENT_MAX_REQUEST_BYTES", "8000000"))
MAX_HISTORY_MESSAGES = int(os.environ.get("AGENT_MAX_HISTORY_MESSAGES", "40"))
MAX_SESSIONS = int(os.environ.get("AGENT_MAX_SESSIONS", "100"))
MAX_TOOL_ROUNDS = int(os.environ.get("AGENT_MAX_TOOL_ROUNDS", "4"))
MAX_PATH_CHARS = 240
MAX_TOOL_CONTENT_BYTES = int(os.environ.get("AGENT_MAX_TOOL_CONTENT_BYTES", "5000000"))


@dataclass
class Session:
    session_id: str
    client_name: str
    workspace_root: str
    history: List[Dict[str, str]] = field(default_factory=list)
    pending_tool_calls: List[Dict[str, Any]] = field(default_factory=list)
    tool_rounds: int = 0
    file_intent_allowed: bool = False
    lock: threading.Lock = field(default_factory=threading.Lock, repr=False)


SESSIONS: Dict[str, Session] = {}
SESSIONS_LOCK = threading.Lock()


def make_tool_call(name: str, args: Dict[str, Any]) -> Dict[str, Any]:
    validate_tool_call(name, args)
    return {
        "id": f"call-{uuid.uuid4().hex[:8]}",
        "name": name,
        "args": args,
    }


def build_mock_hello_world_plan() -> List[Dict[str, Any]]:
    index_html = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello World</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <main class="hero">
    <p class="eyebrow">AIBOX Offline Agent Demo</p>
    <h1>Hello, world.</h1>
    <p>This site was generated by a remote offline agent and written on your PC.</p>
    <button id="hello-button">Click me</button>
  </main>
  <script src="script.js"></script>
</body>
</html>
"""
    style_css = """body {
  margin: 0;
  min-height: 100vh;
  display: grid;
  place-items: center;
  font-family: Georgia, serif;
  background:
    radial-gradient(circle at top, #f3d9b1, transparent 30%),
    linear-gradient(135deg, #1d3557, #457b9d 60%, #a8dadc);
  color: #f8f9fa;
}

.hero {
  width: min(90vw, 42rem);
  padding: 3rem;
  border-radius: 24px;
  background: rgba(13, 27, 42, 0.72);
  box-shadow: 0 24px 60px rgba(0, 0, 0, 0.35);
  text-align: center;
}

.eyebrow {
  text-transform: uppercase;
  letter-spacing: 0.18em;
  font-size: 0.8rem;
  opacity: 0.8;
}

h1 {
  margin: 0.3rem 0 1rem;
  font-size: clamp(2.5rem, 8vw, 4.5rem);
}

button {
  margin-top: 1rem;
  border: 0;
  border-radius: 999px;
  padding: 0.85rem 1.4rem;
  font-size: 1rem;
  cursor: pointer;
  color: #0d1b2a;
  background: #f1fa8c;
}
"""
    script_js = """document.getElementById('hello-button').addEventListener('click', () => {
  window.alert('Hello from your offline agent demo.');
});
"""
    return [
        make_tool_call("write_file", {"path": "index.html", "content": index_html}),
        make_tool_call("write_file", {"path": "style.css", "content": style_css}),
        make_tool_call("write_file", {"path": "script.js", "content": script_js}),
    ]


def build_pretty_hello_world_plan() -> List[Dict[str, Any]]:
    index_html = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello World</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <main class="card">
    <p class="eyebrow">Offline Agent Demo</p>
    <h1>Hello, world.</h1>
    <p class="lead">A small site generated by the remote agent and written on your PC.</p>
    <button id="hello-button">Say hello</button>
  </main>
  <script src="script.js"></script>
</body>
</html>
"""
    style_css = """* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 2rem;
  font-family: Georgia, serif;
  color: #f7f3eb;
  background:
    radial-gradient(circle at top left, rgba(255, 214, 165, 0.35), transparent 28%),
    radial-gradient(circle at bottom right, rgba(90, 169, 230, 0.3), transparent 30%),
    linear-gradient(135deg, #102542 0%, #1f4068 55%, #3b6978 100%);
}

.card {
  width: min(92vw, 44rem);
  padding: 3rem;
  border-radius: 28px;
  background: rgba(8, 15, 26, 0.72);
  border: 1px solid rgba(255, 255, 255, 0.14);
  box-shadow: 0 30px 80px rgba(0, 0, 0, 0.3);
  text-align: center;
  backdrop-filter: blur(8px);
}

.eyebrow {
  margin: 0 0 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.22em;
  font-size: 0.78rem;
  color: #ffd6a5;
}

h1 {
  margin: 0;
  font-size: clamp(2.8rem, 9vw, 5rem);
  line-height: 0.95;
}

.lead {
  margin: 1.25rem auto 0;
  max-width: 32rem;
  font-size: 1.1rem;
  line-height: 1.6;
  color: rgba(247, 243, 235, 0.88);
}

button {
  margin-top: 1.6rem;
  padding: 0.9rem 1.4rem;
  border: 0;
  border-radius: 999px;
  font-size: 1rem;
  font-weight: 700;
  color: #102542;
  background: linear-gradient(135deg, #ffd6a5, #ffef9f);
  cursor: pointer;
  box-shadow: 0 12px 24px rgba(255, 214, 165, 0.25);
}

button:hover {
  transform: translateY(-1px);
}
"""
    script_js = """document.getElementById('hello-button').addEventListener('click', () => {
  window.alert('Hello from your offline agent.');
});
"""
    return [
        make_tool_call("write_file", {"path": "index.html", "content": index_html}),
        make_tool_call("write_file", {"path": "style.css", "content": style_css}),
        make_tool_call("write_file", {"path": "script.js", "content": script_js}),
    ]


class AgentBackend:
    def create_response(self, session: Session) -> Dict[str, Any]:
        raise NotImplementedError


class MockBackend(AgentBackend):
    def create_response(self, session: Session) -> Dict[str, Any]:
        last_user_message = _last_message(session.history, "user")
        if not last_user_message:
            return {
                "reply": "No user message found.",
                "tool_calls": [],
                "done": True,
            }

        lowered = last_user_message.lower()
        if "hello" in lowered and "site" in lowered:
            return {
                "reply": "I will create a minimal hello world site in your PC workspace.",
                "tool_calls": build_mock_hello_world_plan(),
                "done": False,
            }
        if "list" in lowered and "files" in lowered:
            return {
                "reply": "I will inspect the files in your selected workspace.",
                "tool_calls": [make_tool_call("list_dir", {"path": "."})],
                "done": False,
            }
        return {
            "reply": (
                "The mock backend currently supports simple site generation and "
                "workspace listing. Try 'Create a hello world site'."
            ),
            "tool_calls": [],
            "done": True,
        }


class OpenAICompatBackend(AgentBackend):
    def __init__(self, base_url: str, model: str, api_key: str = "local-demo") -> None:
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.api_key = api_key

    def create_response(self, session: Session) -> Dict[str, Any]:
        system_prompt = build_system_prompt(session)
        messages = [{"role": "system", "content": system_prompt}]
        messages.extend(session.history)

        payload = {
            "model": self.model,
            "temperature": 0.2,
            "messages": messages,
        }
        data = json.dumps(payload).encode("utf-8")
        request = urllib.request.Request(
            f"{self.base_url}/v1/chat/completions",
            data=data,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.api_key}",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=120) as response:
                raw = response.read().decode("utf-8")
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"model backend HTTP {exc.code}: {body}") from exc
        except urllib.error.URLError as exc:
            raise RuntimeError(f"model backend network error: {exc.reason}") from exc

        payload = json.loads(raw)
        try:
            content = payload["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as exc:
            raise RuntimeError(f"unexpected model response: {payload}") from exc

        parsed = parse_agent_json(content)
        reply = str(parsed.get("reply", "")).strip()
        raw_tool_calls = parsed.get("tool_calls", [])
        tool_calls = []
        for item in raw_tool_calls:
            if not isinstance(item, dict):
                continue
            name = item.get("name")
            args = item.get("args", {})
            if not isinstance(name, str) or not isinstance(args, dict):
                continue
            try:
                tool_calls.append(make_tool_call(name, args))
            except ValueError:
                continue
        done = bool(parsed.get("done", not tool_calls))
        return {
            "reply": reply or "Model returned no reply.",
            "tool_calls": tool_calls,
            "done": done and not tool_calls,
        }


def _last_message(history: List[Dict[str, str]], role: str) -> str:
    for entry in reversed(history):
        if entry.get("role") == role:
            return entry.get("content", "")
    return ""


def try_builtin_response(session: Session) -> Optional[Dict[str, Any]]:
    if session.tool_rounds > 0:
        return None

    last_user_message = _last_message(session.history, "user").strip()
    if not last_user_message:
        return None

    lowered = last_user_message.lower()
    if lowered in {"hi", "hello", "hey", "hi!", "hello!", "hey!"}:
        return {
            "reply": "Hello. Tell me what you want to build or change in your workspace.",
            "tool_calls": [],
            "done": True,
        }

    if any(
        phrase in lowered
        for phrase in [
            "what is your model",
            "what model are you",
            "who are you",
            "what can you do",
            "help",
            "capabilities",
        ]
    ):
        model_name = os.environ.get("MODEL_NAME", "local-model")
        return {
            "reply": (
                f"I am the AIBOX remote agent running on linaro, currently backed by `{model_name}`. "
                "I can chat, inspect files in your selected workspace, and create or update local project files on this PC when you explicitly ask me to build or change something. "
                "I should not write files for general questions or small talk."
            ),
            "tool_calls": [],
            "done": True,
        }

    hello_world_request = (
        ("hello world" in lowered or "hello, world" in lowered)
        and any(token in lowered for token in ["site", "website", "web", "page", "html", "pretty"])
    )
    if hello_world_request:
        return {
            "reply": "I will create a small styled hello world site in your PC workspace.",
            "tool_calls": build_pretty_hello_world_plan(),
            "done": False,
        }

    return None


def build_system_prompt(session: Session) -> str:
    tool_lines = []
    for tool in TOOLS:
        tool_lines.append(f"- {tool['name']}: {tool['description']}")
        for arg_name, arg_help in tool["args"].items():
            tool_lines.append(f"  arg {arg_name}: {arg_help}")
    tool_block = "\n".join(tool_lines)
    return (
        "You are an offline coding and automation agent running on a remote device.\n"
        "You do not have direct filesystem access. The user's PC executes local tools.\n"
        "Stay within the user's selected workspace.\n"
        "Be concise and action-oriented.\n"
        "Available tools:\n"
        f"{tool_block}\n\n"
        f"Client name: {session.client_name}\n"
        f"Workspace root on client: {session.workspace_root}\n\n"
        f"File changes allowed for the current user turn: {str(session.file_intent_allowed).lower()}\n\n"
        "Always respond with exactly one JSON object matching this shape:\n"
        "{\n"
        '  "reply": "short assistant message",\n'
        '  "tool_calls": [\n'
        '    {"name": "tool_name", "args": {"key": "value"}}\n'
        "  ],\n"
        '  "done": true\n'
        "}\n"
        "Rules:\n"
        "- For greetings or small talk, reply normally with no tool calls.\n"
        "- For questions about your identity, model, or capabilities, reply normally with no tool calls.\n"
        "- If file changes are not allowed for the current user turn, return no tool calls.\n"
        "- Only use tools when the user explicitly wants files inspected, created, or changed.\n"
        "- If a tool is needed, put it in tool_calls and set done to false.\n"
        "- If the task is complete, return no tool_calls and set done to true.\n"
        "- Never wrap JSON in markdown.\n"
        "- Never invent tools outside the allowed list.\n"
        "- Never invent placeholder files such as example.txt or output.txt unless the user asked for them.\n"
        "- If creating a new web page, write complete files such as index.html, style.css, and script.js.\n"
        "- Do not read files before creating them unless the user explicitly asked to edit an existing file.\n"
        "- Use forward slashes in file paths in JSON.\n"
        "- For website tasks, prefer writing complete files with write_file.\n"
    )


def parse_agent_json(content: str) -> Dict[str, Any]:
    stripped = content.strip()
    candidates = [stripped]

    fenced = re.search(r"```(?:json)?\s*(\{.*\})\s*```", stripped, flags=re.DOTALL)
    if fenced:
        candidates.append(fenced.group(1))

    start = stripped.find("{")
    end = stripped.rfind("}")
    if start != -1 and end != -1 and end > start:
        candidates.append(stripped[start : end + 1])

    for candidate in candidates:
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            repaired = repair_json_like_string(candidate)
            if repaired != candidate:
                try:
                    return json.loads(repaired)
                except json.JSONDecodeError:
                    pass

    return {
        "reply": stripped or "The model returned an empty response.",
        "tool_calls": [],
        "done": True,
    }


def validate_relative_path(value: Any) -> str:
    if not isinstance(value, str):
        raise ValueError("tool path must be a string")
    path = value.strip()
    if not path:
        raise ValueError("tool path is empty")
    if len(path) > MAX_PATH_CHARS:
        raise ValueError("tool path is too long")
    if "\x00" in path:
        raise ValueError("tool path contains a null byte")
    normalized = path.replace("\\", "/")
    if normalized.startswith("/") or re.match(r"^[A-Za-z]:", normalized):
        raise ValueError("tool path must be relative")
    parts = [part for part in normalized.split("/") if part not in {"", "."}]
    if any(part == ".." for part in parts):
        raise ValueError("tool path must not contain '..'")
    return normalized or "."


def validate_tool_call(name: Any, args: Any) -> None:
    if not isinstance(name, str) or name not in ALLOWED_TOOL_NAMES:
        raise ValueError(f"unsupported tool: {name}")
    if not isinstance(args, dict):
        raise ValueError("tool args must be an object")
    if name in {"list_dir", "read_file"}:
        validate_relative_path(args.get("path", "."))
    if name == "write_file":
        validate_relative_path(args.get("path"))
        content = args.get("content")
        if not isinstance(content, str):
            raise ValueError("write_file content must be a string")
        if len(content.encode("utf-8")) > MAX_TOOL_CONTENT_BYTES:
            raise ValueError("write_file content is too large")


def trim_history(session: Session) -> None:
    if len(session.history) > MAX_HISTORY_MESSAGES:
        session.history = session.history[-MAX_HISTORY_MESSAGES:]


def repair_json_like_string(candidate: str) -> str:
    repaired = candidate.replace("\r\n", "\n")
    repaired = re.sub(r"(?<!\\)\\(?![\"\\/bfnrtu])", r"\\\\", repaired)
    return repaired


def backend_from_env() -> AgentBackend:
    backend_name = os.environ.get("AGENT_BACKEND", "mock").strip().lower()
    if backend_name == "mock":
        return MockBackend()
    if backend_name == "openai_compat":
        base_url = os.environ.get("MODEL_BASE_URL", "http://127.0.0.1:8080")
        model = os.environ.get("MODEL_NAME", "local-model")
        api_key = os.environ.get("MODEL_API_KEY", "local-demo")
        return OpenAICompatBackend(base_url=base_url, model=model, api_key=api_key)
    raise RuntimeError(f"unsupported backend: {backend_name}")


BACKEND = backend_from_env()


def run_agent_turn(session: Session) -> Dict[str, Any]:
    builtin = try_builtin_response(session)
    if builtin is not None:
        session.pending_tool_calls = builtin.get("tool_calls", [])
        session.history.append({"role": "assistant", "content": builtin.get("reply", "")})
        trim_history(session)
        return builtin

    response = BACKEND.create_response(session)
    if not session.file_intent_allowed and response.get("tool_calls"):
        response = {
            "reply": (
                "I can answer questions directly, but I will only inspect or modify workspace files when you explicitly ask me to build, create, edit, or change something."
            ),
            "tool_calls": [],
            "done": True,
        }
    if session.tool_rounds >= MAX_TOOL_ROUNDS and response.get("tool_calls"):
        response = {
            "reply": (
                "I could not confidently continue after the last tool step. "
                "Please ask for a more specific file change."
            ),
            "tool_calls": [],
            "done": True,
        }
    session.pending_tool_calls = response.get("tool_calls", [])
    session.history.append({"role": "assistant", "content": response.get("reply", "")})
    if not session.pending_tool_calls:
        session.tool_rounds = 0
    trim_history(session)
    return response


def append_tool_results(session: Session, results: List[Dict[str, Any]]) -> None:
    pending_ids = {call.get("id") for call in session.pending_tool_calls}
    summary: List[Dict[str, Any]] = []
    for result in results:
        tool_call_id = result.get("tool_call_id", "unknown")
        if pending_ids and tool_call_id not in pending_ids:
            continue
        summary.append(
            {
                "tool_call_id": tool_call_id,
                "ok": bool(result.get("ok")),
                "output": str(result.get("output", "")),
            }
        )
    session.history.append({"role": "tool", "content": json.dumps(summary, ensure_ascii=True)})
    session.pending_tool_calls = []
    session.tool_rounds += 1


def write_only_success_response(tool_calls: List[Dict[str, Any]], results: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    if not tool_calls:
        return None
    if any(call.get("name") != "write_file" for call in tool_calls):
        return None
    result_by_id = {result.get("tool_call_id"): result for result in results if isinstance(result, dict)}
    if not all(result_by_id.get(call.get("id"), {}).get("ok") for call in tool_calls):
        return None
    paths = [str(call.get("args", {}).get("path", "")).strip() for call in tool_calls]
    paths = [path for path in paths if path]
    if paths:
        return {
            "reply": "Done. Updated: " + ", ".join(paths),
            "tool_calls": [],
            "done": True,
        }
    return {"reply": "Done. Updated the requested workspace files.", "tool_calls": [], "done": True}


def message_allows_file_intent(message: str) -> bool:
    lowered = message.lower()
    intent_terms = [
        "create",
        "build",
        "make",
        "write",
        "generate",
        "edit",
        "change",
        "update",
        "modify",
        "fix",
        "patch",
        "add",
        "remove",
        "delete",
        "refactor",
        "implement",
        "list files",
        "show files",
        "read file",
        "open file",
    ]
    return any(term in lowered for term in intent_terms)


class AgentHandler(BaseHTTPRequestHandler):
    server_version = "OfflineAgentDemo/0.2"

    def do_POST(self) -> None:
        if not self._authorized():
            self._send_json(HTTPStatus.UNAUTHORIZED, {"error": "unauthorized"})
            return
        try:
            payload = self._read_json()
        except ValueError as exc:
            self._send_json(HTTPStatus.BAD_REQUEST, {"error": str(exc)})
            return

        if self.path == "/session/start":
            self._handle_session_start(payload)
            return
        if self.path == "/session/message":
            self._handle_session_message(payload)
            return
        if self.path == "/session/tools":
            self._handle_session_tools(payload)
            return

        self._send_json(HTTPStatus.NOT_FOUND, {"error": "unknown endpoint"})

    def do_GET(self) -> None:
        if self.path == "/health":
            backend_name = os.environ.get("AGENT_BACKEND", "mock")
            self._send_json(
                HTTPStatus.OK,
                {"status": "ok", "sessions": len(SESSIONS), "backend": backend_name},
            )
            return
        self._send_json(HTTPStatus.NOT_FOUND, {"error": "unknown endpoint"})

    def log_message(self, fmt: str, *args: Any) -> None:
        sys.stdout.write("%s - - [%s] %s\n" % (self.address_string(), self.log_date_time_string(), fmt % args))

    def _authorized(self) -> bool:
        expected = os.environ.get("AGENT_TOKEN", "").strip()
        if not expected:
            return True
        supplied = self.headers.get("X-AIBOX-Token", "").strip()
        return hmac.compare_digest(supplied, expected)

    def _handle_session_start(self, payload: Dict[str, Any]) -> None:
        client_name = str(payload.get("client_name", "unknown-client")).strip()[:120] or "unknown-client"
        workspace_root = str(payload.get("workspace_root", "")).strip()[:500]
        session_id = uuid.uuid4().hex
        with SESSIONS_LOCK:
            while len(SESSIONS) >= MAX_SESSIONS:
                oldest = next(iter(SESSIONS))
                del SESSIONS[oldest]
            SESSIONS[session_id] = Session(
                session_id=session_id,
                client_name=client_name,
                workspace_root=workspace_root,
            )
        self._send_json(HTTPStatus.OK, {"session_id": session_id})

    def _handle_session_message(self, payload: Dict[str, Any]) -> None:
        session = self._get_session(payload)
        if session is None:
            return
        message = str(payload.get("message", "")).strip()
        if not message:
            self._send_json(HTTPStatus.BAD_REQUEST, {"error": "message is empty"})
            return
        with session.lock:
            session.tool_rounds = 0
            session.file_intent_allowed = message_allows_file_intent(message)
            session.history.append({"role": "user", "content": message})
            try:
                response = run_agent_turn(session)
            except Exception as exc:
                self._send_json(HTTPStatus.INTERNAL_SERVER_ERROR, {"error": str(exc)})
                return
        self._send_json(HTTPStatus.OK, response)

    def _handle_session_tools(self, payload: Dict[str, Any]) -> None:
        session = self._get_session(payload)
        if session is None:
            return
        results = payload.get("results", [])
        if not isinstance(results, list):
            self._send_json(HTTPStatus.BAD_REQUEST, {"error": "results must be a list"})
            return
        with session.lock:
            completed_calls = list(session.pending_tool_calls)
            append_tool_results(session, results)
            response = write_only_success_response(completed_calls, results)
            if response is None:
                try:
                    response = run_agent_turn(session)
                except Exception as exc:
                    self._send_json(HTTPStatus.INTERNAL_SERVER_ERROR, {"error": str(exc)})
                    return
            else:
                session.history.append({"role": "assistant", "content": response["reply"]})
                session.tool_rounds = 0
                trim_history(session)
        self._send_json(HTTPStatus.OK, response)

    def _get_session(self, payload: Dict[str, Any]) -> Optional[Session]:
        session_id = str(payload.get("session_id", "")).strip()
        with SESSIONS_LOCK:
            session = SESSIONS.get(session_id)
        if session is None:
            self._send_json(HTTPStatus.BAD_REQUEST, {"error": "invalid session_id"})
            return None
        return session

    def _read_json(self) -> Dict[str, Any]:
        length = int(self.headers.get("Content-Length", "0"))
        if length <= 0:
            raise ValueError("missing request body")
        if length > MAX_REQUEST_BYTES:
            raise ValueError(f"request body exceeds {MAX_REQUEST_BYTES} bytes")
        body = self.rfile.read(length)
        try:
            data = json.loads(body)
        except json.JSONDecodeError as exc:
            raise ValueError(f"invalid JSON: {exc.msg}") from exc
        if not isinstance(data, dict):
            raise ValueError("JSON body must be an object")
        return data

    def _send_json(self, status: HTTPStatus, payload: Dict[str, Any]) -> None:
        encoded = json.dumps(payload).encode("utf-8")
        self.send_response(status.value)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(encoded)))
        self.end_headers()
        self.wfile.write(encoded)


def main() -> None:
    global BACKEND
    parser = argparse.ArgumentParser(description="Offline agent demo server")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8765)
    args = parser.parse_args()

    try:
        BACKEND = backend_from_env()
    except Exception as exc:
        print(f"Failed to initialize backend: {exc}", file=sys.stderr)
        sys.exit(1)

    server = ThreadingHTTPServer((args.host, args.port), AgentHandler)
    print(
        "Offline agent demo server listening on "
        f"http://{args.host}:{args.port} using backend={os.environ.get('AGENT_BACKEND', 'mock')}"
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
